# CMake generated Testfile for 
# Source directory: /workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib
# Build directory: /workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[CMakeLib.testArgumentParser]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testArgumentParser")
set_tests_properties([=[CMakeLib.testArgumentParser]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestBinPacker]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testCTestBinPacker")
set_tests_properties([=[CMakeLib.testCTestBinPacker]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceAllocator]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testCTestResourceAllocator")
set_tests_properties([=[CMakeLib.testCTestResourceAllocator]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceSpec]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testCTestResourceSpec" "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testCTestResourceSpec]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceGroups]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testCTestResourceGroups")
set_tests_properties([=[CMakeLib.testCTestResourceGroups]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testGccDepfileReader]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testGccDepfileReader" "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testGccDepfileReader]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testGeneratedFileStream]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testGeneratedFileStream")
set_tests_properties([=[CMakeLib.testGeneratedFileStream]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testJSONHelpers]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testJSONHelpers")
set_tests_properties([=[CMakeLib.testJSONHelpers]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testRST]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testRST" "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testRST]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testRange]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testRange")
set_tests_properties([=[CMakeLib.testRange]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testOptional]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testOptional")
set_tests_properties([=[CMakeLib.testOptional]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testString]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testString")
set_tests_properties([=[CMakeLib.testString]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testStringAlgorithms]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testStringAlgorithms")
set_tests_properties([=[CMakeLib.testStringAlgorithms]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testSystemTools]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testSystemTools")
set_tests_properties([=[CMakeLib.testSystemTools]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUTF8]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testUTF8")
set_tests_properties([=[CMakeLib.testUTF8]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testXMLParser]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testXMLParser")
set_tests_properties([=[CMakeLib.testXMLParser]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testXMLSafe]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testXMLSafe")
set_tests_properties([=[CMakeLib.testXMLSafe]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testFindPackageCommand]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testFindPackageCommand")
set_tests_properties([=[CMakeLib.testFindPackageCommand]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVProcessChain]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testUVProcessChain" "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/testUVProcessChainHelper")
set_tests_properties([=[CMakeLib.testUVProcessChain]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVRAII]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testUVRAII")
set_tests_properties([=[CMakeLib.testUVRAII]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVStreambuf]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testUVStreambuf" "/workspaces/OdysseyEden/cmake-3.27.0/bin/cmake")
set_tests_properties([=[CMakeLib.testUVStreambuf]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtMemory]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testCMExtMemory")
set_tests_properties([=[CMakeLib.testCMExtMemory]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtAlgorithm]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testCMExtAlgorithm")
set_tests_properties([=[CMakeLib.testCMExtAlgorithm]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtEnumSet]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testCMExtEnumSet")
set_tests_properties([=[CMakeLib.testCMExtEnumSet]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testList]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testList")
set_tests_properties([=[CMakeLib.testList]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerAdapter]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testDebuggerAdapter")
set_tests_properties([=[CMakeLib.testDebuggerAdapter]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerAdapterPipe]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testDebuggerAdapterPipe")
set_tests_properties([=[CMakeLib.testDebuggerAdapterPipe]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerBreakpointManager]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testDebuggerBreakpointManager")
set_tests_properties([=[CMakeLib.testDebuggerBreakpointManager]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerVariables]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testDebuggerVariables")
set_tests_properties([=[CMakeLib.testDebuggerVariables]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerVariablesHelper]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testDebuggerVariablesHelper")
set_tests_properties([=[CMakeLib.testDebuggerVariablesHelper]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerVariablesManager]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLibTests" "testDebuggerVariablesManager")
set_tests_properties([=[CMakeLib.testDebuggerVariablesManager]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;79;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerNamedPipe-Project]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/testDebuggerNamedPipe" "/workspaces/OdysseyEden/cmake-3.27.0/bin/cmake" "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/DebuggerSample" "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/DebuggerSample")
set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Project]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;102;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerNamedPipe-Script]=] "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/testDebuggerNamedPipe" "/workspaces/OdysseyEden/cmake-3.27.0/bin/cmake" "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/DebuggerSample/script.cmake")
set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Script]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;102;add_test;/workspaces/OdysseyEden/cmake-3.27.0/Tests/CMakeLib/CMakeLists.txt;0;")
subdirs("PseudoMemcheck")
